
export const classes = [
'Arcanista',
'Bárbaro',
'Bardo',
'Bucaneiro',
'Caçador',
'Cavaleiro',
'Clérigo',
'Druida',
'Guerreiro',
'Inventor',
'Ladino',
'Lutador',
'Nobre',
'Paladino',
]

export const racas = [
    'Aberrante',
    'Aggelus',
    'Anão',
    'Bugbears',
    'Caçadoras',
    'Centauros',
    'Ceratops',
    'Dahllan',
    'Elfo',
    'Elfo de Gelo',
    'Elfo Negro',
    'Elfos do Mar',
    'Elfos Sombrios',
    'Elfos-do-Céu',
    'Feithnari',
    'Finntroll',
    'Gigante',
    'Gnoll',
    'Gnomos',
    'Gnomos das Cavernas',
    'Goblin',
    'Golem',
    'Halflings',
    'Hanyô',
    'Henge',
    'Hengeyokais',
    'Herdeiros do Lobo',
    'Hobgoblin',
    'Homens-Lagarto',
    'Humano',
    'Hynnes',
    'Kaijin',
    'Kathos',
    'Kliren',
    'Kobolds',
    'Lefou',
    'Mashin',
    'Medusa',
    'Meio Elfos-do-Mar',
    'Meio Ogro',
    'Meio-Dríade',
    'Meio-Elfo',
    'Meio-Orcs',
    'Minaques',
    'Minauros',
    'Minotauro',
    'Moreau',
    'Nagah',
    'Nezumi',
    'Nimbus',
    'Orc',
    'Osteon',
    'Povos-Trovão',
    'Pteros',
    'Qareen',
    'Quellons',
    'Ryuujin',
    'Sereia/tritão',
    'Sereias',
    'Sklirynei',
    'Sprites',
    'Sulfure',
    'Thri-Kreen',
    'Trogs',
    'Vanara',
    'Vardak',
    'Velocis']
