export const peronagens = [ { "characterName": "teste nome ", "race": "teste raça", "origin": "teste origem", "characterClass": "teste classe", "level": 6, "deity": "teste divindade", "foto": "", "attributes": { "strength": 12, "dexterity": 11, "constitution": 9, "intelligence": 8, "wisdom": 11, "charisma": 10 }, "skills": { "acrobatics": { "trained": true, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "animalHandling": { "trained": false, "level": 3, "modAtributo": 10, "other": 0, "treino": 0, "total": 0 }, "athletics": { "trained": false, "level": 3, "modAtributo": 12, "other": 0, "treino": 0, "total": 0 }, "performance": { "trained": false, "level": 3, "modAtributo": 10, "other": 0, "treino": 0, "total": 0 }, "ride": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "knowledge": { "trained": false, "level": 3, "modAtributo": 8, "other": 0, "treino": 0, "total": 0 }, "heal": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "diplomacy": { "trained": false, "level": 3, "modAtributo": 10, "other": 0, "treino": 0, "total": 0 }, "deception": { "trained": false, "level": 3, "modAtributo": 10, "other": 0, "treino": 0, "total": 0 }, "fortitude": { "trained": false, "level": 3, "modAtributo": 9, "other": 0, "treino": 0, "total": 0 }, "insight": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "investigation": { "trained": false, "level": 3, "modAtributo": 8, "other": 0, "treino": 0, "total": 0 }, "gambling": { "trained": false, "level": 3, "modAtributo": 10, "other": 0, "treino": 0, "total": 0 }, "thievery": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "fight": { "trained": false, "level": 3, "modAtributo": 12, "other": 0, "treino": 0, "total": 0 }, "arcana": { "trained": false, "level": 3, "modAtributo": 8, "other": 0, "treino": 0, "total": 0 }, "nobility": { "trained": false, "level": 3, "modAtributo": 8, "other": 0, "treino": 0, "total": 0 }, "perception": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "piloting": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "archery": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "reflex": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "religion": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "survival": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "will": { "trained": false, "level": 3, "modAtributo": 11, "other": 0, "treino": 0, "total": 0 }, "craft1": { "trained": false, "level": 3, "modAtributo": 0, "other": 0, "treino": 0, "total": 0 }, "craft2": { "trained": false, "level": 3, "modAtributo": 0, "other": 0, "treino": 0, "total": 0 } }, "abilities": [], "equipment": [], "background": [], "spells": [], "attacks": [], "defenses": 10, "id": 1 } ];

export const classes = [
'Arcanista',
'Bárbaro',
'Bardo',
'Bucaneiro',
'Caçador',
'Cavaleiro',
'Clérigo',
'Druida',
'Guerreiro',
'Inventor',
'Ladino',
'Lutador',
'Nobre',
'Paladino',
]

export const racas = [
    'Aberrante',
    'Aggelus',
    'Anão',
    'Bugbears',
    'Caçadoras',
    'Centauros',
    'Ceratops',
    'Dahllan',
    'Elfo',
    'Elfo de Gelo',
    'Elfo Negro',
    'Elfos do Mar',
    'Elfos Sombrios',
    'Elfos-do-Céu',
    'Feithnari',
    'Finntroll',
    'Gigante',
    'Gnoll',
    'Gnomos',
    'Gnomos das Cavernas',
    'Goblin',
    'Golem',
    'Halflings',
    'Hanyô',
    'Henge',
    'Hengeyokais',
    'Herdeiros do Lobo',
    'Hobgoblin',
    'Homens-Lagarto',
    'Humano',
    'Hynnes',
    'Kaijin',
    'Kathos',
    'Kliren',
    'Kobolds',
    'Lefou',
    'Mashin',
    'Medusa',
    'Meio Elfos-do-Mar',
    'Meio Ogro',
    'Meio-Dríade',
    'Meio-Elfo',
    'Meio-Orcs',
    'Minaques',
    'Minauros',
    'Minotauro',
    'Moreau',
    'Nagah',
    'Nezumi',
    'Nimbus',
    'Orc',
    'Osteon',
    'Povos-Trovão',
    'Pteros',
    'Qareen',
    'Quellons',
    'Ryuujin',
    'Sereia/tritão',
    'Sereias',
    'Sklirynei',
    'Sprites',
    'Sulfure',
    'Thri-Kreen',
    'Trogs',
    'Vanara',
    'Vardak',
    'Velocis']
